from . import purchase_order
from . import stock_picking
from . import stock_move
from . import product_template
from . import bts_material_request
from . import inventory_dashboard
from . import inventory_notification
from . import project_project
from . import project_dashboard
