{
    'name': 'Quản lí bảo trì trạm BTS',
    'version': '1.0',
    'summary': 'Quản lí bảo trì trạm BTS',
    'category': 'DTC BTS',
    'author': 'MIS Group',
    'depends': [
        'dtc_bts_base',
        'dtc_bts_inventory',
        'maintenance',
        'mail',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/checklist_data.xml',
        'data/mail_template_migration.xml',
        'data/mail_template_data.xml',
        'data/maintenance_due_cron.xml',
        'views/maintenance_equipment_views.xml',
        'views/maintenance_equipment_bulk_wizard_views.xml',
        'views/project_due_views.xml',
        'views/maintenance_batch_views.xml',
        'views/maintenance_request_views.xml',
        'views/checklist_item_views.xml',
        'views/checklist_result_views.xml',
        'views/repair_proposal_views.xml',
        'views/material_request_views.xml',
        'views/dashboard_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
