from . import project_project
from . import dashboard
from . import dashboard_analytics
from . import maintenance_batch
from . import maintenance_equipment
from . import maintenance_equipment_bulk_wizard
from . import maintenance_request
from . import material_request
from . import checklist_item
from . import checklist_result
from . import repair_proposal
